/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTFUNCTION2 = 3;
  public int JJTVARLIST = 4;
  public int JJTSCALARELEMENT = 5;
  public int JJTARRAYELEMENT = 6;
  public int JJTSTMTLST = 7;
  public int JJTSTMT = 8;
  public int JJTASSIGN = 9;
  public int JJTLHS = 10;
  public int JJTRHS = 11;
  public int JJTARRAYSIZE = 12;
  public int JJTTERM = 13;
  public int JJTEXPRTEST = 14;
  public int JJTWHILE = 15;
  public int JJTIF = 16;
  public int JJTCALL = 17;
  public int JJTARGUMENTLIST = 18;
  public int JJTARGUMENT = 19;
  public int JJTARRAYACCESS = 20;
  public int JJTSCALARACCESS = 21;
  public int JJTINDEX = 22;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Function2",
    "Varlist",
    "ScalarElement",
    "ArrayElement",
    "Stmtlst",
    "Stmt",
    "Assign",
    "Lhs",
    "Rhs",
    "ArraySize",
    "Term",
    "Exprtest",
    "While",
    "If",
    "Call",
    "ArgumentList",
    "Argument",
    "ArrayAccess",
    "ScalarAccess",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=10e903b6cf95a1ba827d9205bb08eb90 (do not edit this line) */
