/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 5.0 */
public interface ParserTreeConstants
{
  public int JJTMODULE = 0;
  public int JJTDECLARATION = 1;
  public int JJTFUNCTION = 2;
  public int JJTRETURN = 3;
  public int JJTPARAMETERS = 4;
  public int JJTVOID = 5;
  public int JJTID = 6;
  public int JJTINTEGER = 7;
  public int JJTARRAYELEMENT = 8;
  public int JJTCALL = 9;
  public int JJTASSIGN = 10;
  public int JJTARRAY = 11;
  public int JJTARRAYACCESS = 12;
  public int JJTARRAYSIZE = 13;
  public int JJTEXPRTEST = 14;
  public int JJTWHILE = 15;
  public int JJTIF = 16;
  public int JJTELSE = 17;
  public int JJTARGUMENTLIST = 18;
  public int JJTARGUMENT = 19;
  public int JJTINDEX = 20;


  public String[] jjtNodeName = {
    "Module",
    "Declaration",
    "Function",
    "Return",
    "Parameters",
    "void",
    "Id",
    "Integer",
    "ArrayElement",
    "Call",
    "Assign",
    "Array",
    "ArrayAccess",
    "ArraySize",
    "Exprtest",
    "While",
    "If",
    "Else",
    "ArgumentList",
    "Argument",
    "Index",
  };
}
/* JavaCC - OriginalChecksum=5c58812768982836662e5a49c3ead256 (do not edit this line) */
