/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.3 */
/* JavaCCOptions:MULTI=false,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SimpleNode implements Node {

  protected Node parent;
  protected Node[] children;
  protected int id;
  protected Object value;
  protected Parser parser;
  
  //Added
  public String val = "Undefined";

  public SimpleNode(int i) {
    id = i;
  }

  public SimpleNode(Parser p, int i) {
    this(i);
    parser = p;
  }

  public void jjtOpen() {
  }

  public void jjtClose() {
  }

  public void jjtSetParent(Node n) { parent = n; }
  public Node jjtGetParent() { return parent; }

  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node c[] = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  public Node jjtGetChild(int i) {
    return children[i];
  }

  public int jjtGetNumChildren() {
    return (children == null) ? 0 : children.length;
  }

  public void jjtSetValue(Object value) { this.value = value; }
  public Object jjtGetValue() { return value; }

  /* You can override these two methods in subclasses of SimpleNode to
     customize the way the node appears when the tree is dumped.  If
     your output uses more than one line you should override
     toString(String), otherwise overriding toString() is probably all
     you need to do. */

  public String toString() { return ParserTreeConstants.jjtNodeName[id]; }
  public String toString(String prefix) { return prefix + toString(); }

  /* Override this method if you want to customize how the node dumps
     out its children. */

  public void dump(String prefix) {
    
    if (children != null) {
      switch (this.id){
      case ParserTreeConstants.JJTEXPRTEST:
      	System.out.println(prefix+this.val);
      	break;
      case ParserTreeConstants.JJTASSIGN:
        	System.out.println(prefix+this.val);
        	break;
      case ParserTreeConstants.JJTRHS:
    	if(this.val !="Undefined"){
    		System.out.println(prefix+this.val);
    	}
    	else{
    		prefix = prefix.substring(0, prefix.length()-1);
    	}
      	break;
      case ParserTreeConstants.JJTTERM:
      	if(children.length > 1){
      		SimpleNode aux = (SimpleNode)children[1];
      		switch(aux.id){
      		case ParserTreeConstants.JJTARRAYACCESS:
      			System.out.println(prefix + "Array");
      		}
      	}
      	else{
      		prefix = prefix.substring(0, prefix.length()-1);
      	}
      	break;
      default:
    	System.out.println(toString(prefix));
      	break;
      
      }
      for (int i = 0; i < children.length; ++i) {
        SimpleNode n = (SimpleNode)children[i];
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }else{System.out.println(toString(prefix) + ": " + this.val);}
  }
}

/* JavaCC - OriginalChecksum=f32205b061e34e2a71252a4fbe0921a7 (do not edit this line) */
